// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW4hyPyA2lPtoCZIKWO2PN5vUqCQ1eWY8',
    appId: '1:312429107987:web:6eb8eabd7d4ee01d7ad8e6',
    messagingSenderId: '312429107987',
    projectId: 'brl-course-review-app',
    authDomain: 'brl-course-review-app.firebaseapp.com',
    storageBucket: 'brl-course-review-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-hprk2YIz1pRIwRjDprvdmQv5_g711Jw',
    appId: '1:312429107987:android:578e7962451467147ad8e6',
    messagingSenderId: '312429107987',
    projectId: 'brl-course-review-app',
    storageBucket: 'brl-course-review-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrylzTLTIWuJedQu6_w45Q8je8B_kuiDo',
    appId: '1:312429107987:ios:421a9135711b15687ad8e6',
    messagingSenderId: '312429107987',
    projectId: 'brl-course-review-app',
    storageBucket: 'brl-course-review-app.appspot.com',
    iosBundleId: 'com.brlakgec.brlCourseReviewApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrylzTLTIWuJedQu6_w45Q8je8B_kuiDo',
    appId: '1:312429107987:ios:4d1082ead4f637d77ad8e6',
    messagingSenderId: '312429107987',
    projectId: 'brl-course-review-app',
    storageBucket: 'brl-course-review-app.appspot.com',
    iosBundleId: 'com.brlakgec.brlCourseReviewApp.RunnerTests',
  );
}
